data:
 build: data
master:
  build: master
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  volumes_from:
    - data
  ports:
    - "8080:8080"
    - "50000:50000"
db:
  build: database
  ports:
    - "3306:3306"
    
sonar:
  build: sonar
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  ports:
    - "9000:9000"
  links:
    - db

